"""Generate an Ollama Modelfile for a converted GGUF.

Why this exists: Ollama does NOT execute the Jinja chat template embedded
in a GGUF (its Go code has no Jinja engine). For Gemma 4 models Ollama has
a native Go renderer (model/renderers/gemma4.go) that handles chat turns,
tool calls, and thinking mode (the request `think` field injects the
`<|think|>` token). `ollama create` auto-detects it from the GGUF's
`general.architecture == "gemma4"` metadata - so a FROM-file import of any
correctly-converted Gemma 4 GGUF gets native chat + thinking with no
template at all. This tool pins the renderer/parser/stop explicitly so the
Modelfile also works on Ollama builds whose arch auto-detect is missing or
misclassifies the small-vs-large variant, and adds the official sampling
parameters.

Verified against ollama/ollama @ 6383a0f (2026-09):
  - server/create.go auto-stamps Renderer/Parser/stop from architecture
  - renderers registry: "gemma4"/"gemma4-large" (large = empty thought block
    when think=false), gemma4.go Thinking() = {false, true}, default false
  - official gemma4 params: temperature 1.0, top_k 64, top_p 0.95
  - llama-server runs --no-jinja on the renderer path; the embedded Jinja
    stays as an unused fallback

Usage:
    python tools/ollama_modelfile.py <model.gguf> [-o Modelfile]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# architecture -> (renderer, parser, stop, sampling defaults, min params for
# the "large" renderer variant). Only archs where pinning matters are listed;
# anything else gets a plain FROM + num_ctx (Ollama auto-detects the rest).
KNOWN = {
    "gemma4": {
        "renderer_large": "gemma4-large",   # empty thought block on think=false
        "renderer_small": "gemma4",
        "large_min_params": 8e9,            # 26B/31B -> large; E2B/E4B -> small
        "parser": "gemma4",
        "stop": "<turn|>",
        "params": {"temperature": "1.0", "top_k": "64", "top_p": "0.95"},
        "note": (
            "Gemma 4 thinking mode: pass \"think\": true in /api/chat (or "
            "--think in the CLI). The renderer injects <|think|>; with "
            "think=false the large variant emits an empty thought block, "
            "exactly like ollama run gemma4:26b."
        ),
    },
}


def read_arch_and_params(gguf: Path) -> tuple[str, int]:
    from gguf import GGUFReader

    r = GGUFReader(str(gguf))
    arch = "llama"
    if "general.architecture" in r.fields:
        arch = bytes(r.fields["general.architecture"].parts[-1]).decode()
    return arch, sum(int(t.n_elements) for t in r.tensors)


def kv_bytes_per_token(gguf: Path) -> int | None:
    """f16 KV-cache bytes per token: layers × kv_heads × head_k × 2 (K+V).

    Reads the arch-prefixed metadata fields (``*.block_count``,
    ``*.attention.head_count_kv``/``head_count``, ``*.attention.key_length``).
    Returns None when the file doesn't carry enough metadata (e.g. a DiT
    GGUF - KV cache is an LLM-serving concept).
    """
    from gguf import GGUFReader

    r = GGUFReader(str(gguf))

    def _int(suffix: str) -> int | None:
        for key, field in r.fields.items():
            if key.endswith(suffix):
                try:
                    return int(field.parts[-1][0])
                except (TypeError, ValueError, IndexError):
                    return None
        return None

    layers = _int(".block_count")
    kv_heads = _int(".attention.head_count_kv") or _int(".attention.head_count")
    head_k = _int(".attention.key_length")
    if layers and kv_heads and head_k:
        return layers * kv_heads * head_k * 2 * 2
    return None


def build_modelfile(gguf: Path, model_name: str = "", num_ctx: int = 32768) -> str:
    gguf = gguf.resolve()
    arch, params = read_arch_and_params(gguf)
    info = KNOWN.get(arch)
    name = model_name or gguf.stem.lower().replace(" ", "-")

    lines = [
        f"# Auto-generated by tools/ollama_modelfile.py",
        f"# Architecture: {arch} ({params / 1e9:.1f}B params)",
        f"# Requires Ollama with native {arch} support (gemma4 landed in 0.20.5+;",
        f"# renderer auto-detect needs a recent build - the RENDERER/PARSER lines",
        f"# below make it explicit). If `ollama create` rejects RENDERER, delete",
        f"# the RENDERER/PARSER lines: recent Ollama auto-detects from the GGUF.",
        f"FROM {gguf}",
    ]
    if info:
        variant = (info["renderer_large"] if params >= info["large_min_params"]
                   else info["renderer_small"])
        lines += [
            f"RENDERER {variant}",
            f"PARSER {info['parser']}",
            f'PARAMETER stop "{info["stop"]}"',
        ]
        for k, v in info["params"].items():
            lines.append(f"PARAMETER {k} {v}")
        lines += ["", f"# {info['note']}"]
    else:
        lines += [
            "",
            "# Architecture not explicitly pinned here - Ollama auto-detects the",
            "# renderer from general.architecture. Check `ollama show --modelfile`",
            "# after create; if chat formatting looks wrong, your Ollama build may",
            "# predate this architecture's renderer.",
        ]
    lines.append(f"PARAMETER num_ctx {num_ctx}")
    kv_per_tok = kv_bytes_per_token(gguf)
    if kv_per_tok:
        kv_total = kv_per_tok * num_ctx
        lines += [
            "",
            f"# KV cache (f16): {kv_per_tok / 1e6:.2f} MB/token -> "
            f"~{kv_total / 1e9:.2f} GB at num_ctx {num_ctx}.",
            "# Serving long contexts on limited VRAM? Shrink the cache with the",
            "# OLLAMA_KV_CACHE_TYPE env var (halves at q8_0, quarters at q4_0):",
            "#   PowerShell:  $env:OLLAMA_KV_CACHE_TYPE=\"q8_0\"; ollama serve",
            "#   bash:        OLLAMA_KV_CACHE_TYPE=q8_0 ollama serve",
            "# or lower num_ctx above (the context, not the model, scales the cache).",
        ]
    lines += [
        "",
        "# Create and run:",
        f"#   ollama create {name} -f Modelfile",
        f"#   ollama run {name} --think",
        "# API:",
        f'#   curl http://localhost:11434/api/chat -d \'{{"model": "{name}", '
        f'"think": true, "messages": [{{"role": "user", "content": "..."}}]}}\'',
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("gguf", type=Path)
    ap.add_argument("-o", "--output", type=Path, default=None,
                    help="Modelfile output path (default: <gguf>.Modelfile)")
    ap.add_argument("--name", default="", help="model name for create/run hints")
    ap.add_argument("--num-ctx", type=int, default=32768)
    args = ap.parse_args(argv)

    if not args.gguf.is_file():
        print(f"not found: {args.gguf}", file=sys.stderr)
        return 1
    out = args.output or args.gguf.with_suffix(".Modelfile")
    out.write_text(build_modelfile(args.gguf, args.name, args.num_ctx), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
